version: '3.8'

services:
  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  nodejs:
    build:
      context: ./node_app
    container_name: nodejs_app
    ports:
      - "3000:3000"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_server
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpressdb
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_server
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_SERVER: mariadb
      PGADMIN_DEFAULT_PORT: 3306
    ports:
      - "5050:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data: